import Head from "next/head";
import { AiFillLinkedin } from "react-icons/ai";
import profilepic from "../public/Fayssal.jpg";
import hlc from "../public/hlc.png";
import hlc_1 from "../public/hlc_2.png";
import estime from "../public/logo_estime.webp";
import estime_1 from "../public/estime_pic.jpg";
import glo_1 from "../public/glo_1.png";
import glo_2 from "../public/glo_2.png";
import glo_3 from "../public/glo_3.png";
import Image from "next/image";
import goto_logo from "../public/goto_logo.svg";
import intact from "../public/Intact_Financial_logo.svg";


console.log('JavaScript debug log');
console.log('eslint is disabled now');


export default function Home() {

  return (
    <div>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Fayssal&apos;s Portfolio</h1>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Fayssal Laghcha
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Software Engineering Intern
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              4th Year Software Engineering Student looking for a fourth internship
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://www.linkedin.com/in/fayssal-laghcha/"><AiFillLinkedin /></a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={profilepic} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div className="bg-white">
            <h3 className="text-3xl py-1 dark:text-white ">Presentation</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200 shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1" >
              I am currently starting my 3rd year at 
              <span className="text-teal-500"> University Laval </span>
              in <span className="text-teal-500">Software Engineering </span>
              and having completed my first internship as a <span className="text-teal-500">Front-end</span> intern at   
              <span className="text-teal-500"> <Image src={hlc} width={80} height={40} /></span>
              , my second one as a <span className="text-teal-500">Full-Stack</span> intern at
              <span className="text-teal-500"> <Image src={goto_logo} width={80} height={40} /></span>
              previously known as LogMeIn,
              and one coming this winter as a <span className="text-teal-500">DevSecOps</span> intern at 
              <span className="text-teal-500"> <Image src={intact} width={80} height={40} /></span>
              I am ready for my next challenge and looking to experiment and learn in the 2024 summer internship.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200 shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              Having successfully completed three full years of Object-Oriented Programming, 
              I became very familiar with
              <span className="text-teal-500"> Java</span>, that i also used a lot in my 2nd internship,
              <span className="text-teal-500"> C++</span>,
              <span className="text-teal-500"> Python</span> and
              <span className="text-teal-500"> Javascript</span>,
              which is also the language i mainly used in my first internship.
              I intend to graduate in December of 2024, with a specialization in Data Science.
            </p>
          </div>
          <div className="">
            <h3 className="text-3xl py-1 dark:text-white ">Professional Experience</h3>
            <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={goto_logo} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  text-teal-500">
                Full-Stack intern
              </h3>
              <p className="py-2">
                In my most recent internship at <span className="text-teal-500">GoTo</span>, I helped maintain a data pipeline of over 5 million contacts.
                Using Java and Typescript, I implemented 2 API calls and a multi-select, multi-delete feature. I also resolved 10+ complex software issues
                and improved endpoint security.
                I gained experience with technologies such as <span className="text-teal-500">Kafka</span>, 
                 <span className="text-teal-500">Springboot</span>, <span className="text-teal-500">Docker</span>, 
                 <span className="text-teal-500">Kubernetes</span>, <span className="text-teal-500">PostgreSQL</span> and many more. 
              </p>
              <div className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200 shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
                <h4 className="py-4 text-teal-600">Skills</h4>
                <p className="text-gray-800 py-1">Java</p>
                <p className="text-gray-800 py-1">Typescript</p>
                <p className="text-gray-800 py-1">Kafka</p>
                <p className="text-gray-800 py-1">PostgreSQL</p>
                <p className="text-gray-800 py-1">APIs</p>
              </div>
            </div>
            </div>
            <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={intact} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  text-teal-500">
                DevSecOps intern
              </h3>
              <p className="py-2">
                In my upcoming internship, this winter at <span className="text-teal-500">Intact Financial Corp.</span>, I will use Java to adopt DevOps principles, automation and
                Cloud technologies. I'll also gain hands-on experience with, Maven and  and contribute to building and deploying
                DevSecOps tools for developers.
                I gained experience with technologies such as <span className="text-teal-500">OpenShift</span>, 
                 <span className="text-teal-500">Spring</span>, <span className="text-teal-500">Docker</span>, 
                 <span className="text-teal-500">SQL</span>, <span className="text-teal-500">Jenkins</span> and many more. 
              </p>
            </div>
            </div>
            <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={hlc} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  text-teal-500">
                Internship in Web Developpement
              </h3>
              <p className="py-2">
                In my first internship, i was tasked with the redesign of a large e-commerce website, owned by <span className="text-teal-500">HLC</span>. 
                I had to start by researching ressources to find a framework that will suit the team&apos;s current and future needs.
                I chose 2 main technologies, <span className="text-teal-500">Vue.js</span> as the main framework and a nice addition, <span className="text-teal-500">Prismic</span>, which enabled me to 
                develop a fully customisable website that can easily be changed by non-programmers. 
                I also documented the process and became acustomed to the <span className="text-teal-500">Agile</span> methodology using the <span className="text-teal-500">Atlassian</span> tools.
              </p>
              <Image src={hlc_1} width={1000} height={462} />
             <div className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200 shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <h4 className="py-4 text-teal-600">Skills</h4>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">Vue.Js</p>
              <p className="text-gray-800 py-1">Prismic</p>
              <p className="text-gray-800 py-1">Azure DevOps</p>
              <p className="text-gray-800 py-1">Kanban/Jira</p>
              </div>
            </div>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={estime} width={180} height={140} />
              <h3 className="text-lg font-medium pt-8 pb-2 text-teal-500">
                Part-time Programming Instructor
              </h3>
              <p className="py-2">
                In my part-time job, I essentially transmit my passion and love for programming to the younger generation. 
                As a programming instructor, I prepare and animate entertaining programming activites or projects
                and do my best to try to spark interest about computers in my students, using languages
                like Python and JavaScript and platforms like MakeCodeArcade and Scratch and 
                for remote classes or various robots for in-person ones.  
              </p>
              <Image src={estime_1} width={400} height={600} />
              <h4 className="py-4 text-teal-600">Skills</h4>
              <p className="text-gray-800 py-1">Animating</p>
              <p className="text-gray-800 py-1">Coding Knowledge</p>
              <p className="text-gray-800 py-1">Teaching</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Projects</h3>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
          <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
            <div className="basis-1/3 flex-1 ">
            <h3 className="text-lg font-medium pt-8 pb-2 text-teal-600">
                Modeling Software in Java
              </h3>
              <p className="py-2">The goal of this project was to create an application that could model a basic house-like structure,
              with the possibility to add various accessories such as a door or a window, change the dimensions and angles of various parts,
              like the angle of the solder ply. Also, the possibility to export the walls as an SVG file, 
              features that enable zooming, the undo/redo, saving and naming files and much more.
              A very complete project, built using UML concepts and the Agile methodology.
               </p>
            
            </div>
            <div className="basis-1/3 flex-1">
            <Image src={glo_1} width={800} height={600} />
            <Image src={glo_2} width={800} height={600} />
            <Image src={glo_3} width={800} height={600} />
            </div>
            <div className="basis-1/3 flex-1">
            
            </div>
            <div className="basis-1/3 flex-1">
             
            
            </div>
            <div className="basis-1/3 flex-1">
             
            </div>
            <div className="basis-1/3 flex-1">
             
            </div>
            </div>

          </div>
        </section>
      </main>
    </div>
  );
}
