import Head from "next/head";
import { AiFillLinkedin } from "react-icons/ai";
import profilepic from "../public/Fayssal.jpg";
import hlc from "../public/hlc.png";
import hlc_1 from "../public/hlc_2.png";
import estime from "../public/logo_estime.webp";
import estime_1 from "../public/estime_pic.jpg";
import glo_1 from "../public/glo_1.png";
import glo_2 from "../public/glo_2.png";
import glo_3 from "../public/glo_3.png";
import Image from "next/image";
import goto_logo from "../public/goto_logo.svg";
import intact from "../public/Intact_Financial_logo.svg";


console.log('JavaScript debug log');
console.log('eslint is disabled now');


export default function Home() {

  return (
    <div>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Fayssal&apos;s Portfolio</h1>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Fayssal Laghcha
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Software Engineer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Back-end Software Engineer with front-end and DevOps experience
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://www.linkedin.com/in/fayssal-laghcha/"><AiFillLinkedin /></a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={profilepic} fill className="object-cover" alt="Fayssal's profile picture" />
            </div>
          </div>
        </section>
<section className="py-10">
  <h3 className="text-3xl font-semibold mb-6 dark:text-white">Presentation</h3>

  <div className="bg-white dark:bg-gray-800 p-6 space-y-6 rounded-xl border border-black/40 dark:border-white/20 shadow-xl">

    {/* BLOCK 1 */}
    <p className="text-gray-800 dark:text-gray-200 leading-relaxed">
      I am a 
      <span className="text-teal-500 font-semibold"> University Laval </span>
      graduate in 
      <span className="text-teal-500 font-semibold"> Software Engineering </span>
      and a Software engineer at 

      <span className="inline-flex items-center mx-1">
        <Image src={goto_logo} width={70} height={35} alt="GoTo logo" />
      </span>

      with a focus on back-end development and DevOps.  
      I completed my first internship as a 
      <span className="text-teal-500 font-semibold"> Front-end </span>
      intern at 

      <span className="inline-flex items-center mx-1">
        <Image src={hlc} width={50} height={15} alt="HLC logo" />
      </span>

      , my second as a 
      <span className="text-teal-500 font-semibold"> Full-Stack </span>
      intern at 

      <span className="inline-flex items-center mx-1">
        <Image src={goto_logo} width={70} height={35} alt="GoTo Logo" />
      </span>

      (previously LogMeIn), then as a 
      <span className="text-teal-500 font-semibold"> DevSecOps </span>
      intern at 

      <span className="inline-flex items-center mx-1">
        <Image src={intact} width={70} height={35} alt="Intact logo" />
      </span>

      and finally returned to  

      <span className="inline-flex items-center mx-1">
        <Image src={goto_logo} width={70} height={35} alt="GoTo Logo" />
      </span>

      as a Front-end intern before being hired full-time.
    </p>
  </div>
  <h3 className="text-3xl font-semibold mb-6 dark:text-white pt-6">Experience</h3>

  <div className="bg-white dark:bg-gray-800 p-6 space-y-6 rounded-xl border border-black/40 dark:border-white/20 shadow-xl">

            <div className="lg:flex gap-10">
  <div className="bg-white dark:bg-gray-800 p-6 space-y-6 rounded-xl border border-black/40 dark:border-white/20 shadow-xl">
              <Image src={goto_logo} width={100} height={100} alt="Goto logo" />
              <h3 className="text-lg font-medium pt-8 pb-2  text-teal-500">
                Full-Stack intern
              </h3>
    <p className="text-gray-800 dark:text-gray-200 leading-relaxed">
                In my most recent internship at <span className="text-teal-500">GoTo</span>, I helped maintain a data pipeline of over 5 million contacts.
                Using Java and Typescript, I implemented 2 API calls and a multi-select, multi-delete feature. I also resolved 10+ complex software issues
                and improved endpoint security.
                I gained experience with technologies such as <span className="text-teal-500">Kafka</span>, 
                 <span className="text-teal-500">Springboot</span>, <span className="text-teal-500">Docker</span>, 
                 <span className="text-teal-500">Kubernetes</span>, <span className="text-teal-500">PostgreSQL</span> and many more. 
              </p>
            </div>
            </div>
            <div className="lg:flex gap-10">
  <div className="bg-white dark:bg-gray-800 p-6 space-y-6 rounded-xl border border-black/40 dark:border-white/20 shadow-xl">
              <Image src={intact} width={100} height={100} alt="intact" />
              <h3 className="text-lg font-medium pt-8 pb-2  text-teal-500">
                DevSecOps intern
              </h3>
              <p className="py-2">
                In my upcoming internship, this winter at <span className="text-teal-500">Intact Financial Corp.</span>, I will use Java to adopt DevOps principles, automation and
                Cloud technologies. I'll also gain hands-on experience with, Maven and  and contribute to building and deploying
                DevSecOps tools for developers.
                I gained experience with technologies such as <span className="text-teal-500">OpenShift</span>, 
                 <span className="text-teal-500">Spring</span>, <span className="text-teal-500">Docker</span>, 
                 <span className="text-teal-500">SQL</span>, <span className="text-teal-500">Jenkins</span> and many more. 
              </p>
            </div>
            </div>
            <div className="lg:flex gap-10">
  <div className="bg-white dark:bg-gray-800 p-6 space-y-6 rounded-xl border border-black/40 dark:border-white/20 shadow-xl">
              <Image src={hlc} width={100} height={100} alt="hlc"/>
              <h3 className="text-lg font-medium pt-8 pb-2  text-teal-500">
                Internship in Web Developpement
              </h3>
              <p className="py-2">
                In my first internship, i was tasked with the redesign of a large e-commerce website, owned by <span className="text-teal-500">HLC</span>. 
                I had to start by researching ressources to find a framework that will suit the team&apos;s current and future needs.
                I chose 2 main technologies, <span className="text-teal-500">Vue.js</span> as the main framework and a nice addition, <span className="text-teal-500">Prismic</span>, which enabled me to 
                develop a fully customisable website that can easily be changed by non-programmers. 
                I also documented the process and became acustomed to the <span className="text-teal-500">Agile</span> methodology using the <span className="text-teal-500">Atlassian</span> tools.
              </p>
              <Image src={hlc_1} width={1000} height={462} alt="hlc"/>
            </div>
            </div>
  <div className="bg-white dark:bg-gray-800 p-6 space-y-6 rounded-xl border border-black/40 dark:border-white/20 shadow-xl">
              <Image src={estime} width={180} height={140} alt="estime"/>
              <h3 className="text-lg font-medium pt-8 pb-2 text-teal-500">
                Part-time Programming Instructor
              </h3>
              <p className="py-2">
                In my part-time job, I essentially transmit my passion and love for programming to the younger generation. 
                As a programming instructor, I prepare and animate entertaining programming activites or projects
                and do my best to try to spark interest about computers in my students, using languages
                like Python and JavaScript and platforms like MakeCodeArcade and Scratch and 
                for remote classes or various robots for in-person ones.  
              </p>
              <Image src={estime_1} width={400} height={600} alt="estime" />
            </div>
          </div>
        </section>
        <section className="py-10">
  <div className="bg-white dark:bg-gray-800 p-6 space-y-6 rounded-xl border border-black/40 dark:border-white/20 shadow-xl">
            <h3 className="text-3xl py-1 dark:text-white ">Projects</h3>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
          <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
            <div className="basis-1/3 flex-1 ">
            <h3 className="text-lg font-medium pt-8 pb-2 text-teal-600">
                Modeling Software in Java
              </h3>
              <p className="py-2">The goal of this project was to create an application that could model a basic house-like structure,
              with the possibility to add various accessories such as a door or a window, change the dimensions and angles of various parts,
              like the angle of the solder ply. Also, the possibility to export the walls as an SVG file, 
              features that enable zooming, the undo/redo, saving and naming files and much more.
              A very complete project, built using UML concepts and the Agile methodology.
               </p>
            
            </div>
            <div className="basis-1/3 flex-1">
            <Image src={glo_1} width={800} height={600} alt="glo" />
            <Image src={glo_2} width={800} height={600} alt="glo" />
            <Image src={glo_3} width={800} height={600} alt="glo" />
            </div>
            <div className="basis-1/3 flex-1">
            
            </div>
            <div className="basis-1/3 flex-1">
             
            
            </div>
            <div className="basis-1/3 flex-1">
             
            </div>
            <div className="basis-1/3 flex-1">
             
            </div>
            </div>

          </div>
          </div>
        </section>
      </main>
    </div>
  );
}
